<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Elsa" Version="3.8.0-preview1" />
    <PackageReference Include="Elsa.Workflows.Core" Version="3.8.0-preview1" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="11.0.0-preview.7.26381.103" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkflowGraph\Graph.csproj" />
  </ItemGroup>

</Project>
